package com.soap.courses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-05-25T23:19:13.452+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://soap.com/courses", name = "CouserPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CouserPort {

    @WebMethod(operationName = "GetCourseDetails")
    @WebResult(name = "GetCourseDetailsResponse", targetNamespace = "http://soap.com/courses", partName = "GetCourseDetailsResponse")
    public GetCourseDetailsResponse getCourseDetails(
        @WebParam(partName = "GetCourseDetailsRequest", name = "GetCourseDetailsRequest", targetNamespace = "http://soap.com/courses")
        GetCourseDetailsRequest getCourseDetailsRequest
    );

    @WebMethod(operationName = "DeleteCourseDetails")
    @WebResult(name = "DeleteCourseDetailsResponse", targetNamespace = "http://soap.com/courses", partName = "DeleteCourseDetailsResponse")
    public DeleteCourseDetailsResponse deleteCourseDetails(
        @WebParam(partName = "DeleteCourseDetailsRequest", name = "DeleteCourseDetailsRequest", targetNamespace = "http://soap.com/courses")
        DeleteCourseDetailsRequest deleteCourseDetailsRequest
    );

    @WebMethod(operationName = "GetAllCourseDetails")
    @WebResult(name = "GetAllCourseDetailsResponse", targetNamespace = "http://soap.com/courses", partName = "GetAllCourseDetailsResponse")
    public GetAllCourseDetailsResponse getAllCourseDetails(
        @WebParam(partName = "GetAllCourseDetailsRequest", name = "GetAllCourseDetailsRequest", targetNamespace = "http://soap.com/courses")
        GetAllCourseDetailsRequest getAllCourseDetailsRequest
    );
}
